/hunter_se:
  controller_manager:
    ros__parameters:
      update_rate: 1000 #Hz

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      steering_trajectory_controller:
        type: joint_trajectory_controller/JointTrajectoryController

      forward_velocity_controller:
        type: forward_command_controller/ForwardCommandController
        
  steering_trajectory_controller:
    ros__parameters:
      joints:
        - front_right_steer_joint
        - front_left_steer_joint
        - center_steer_joint
      interface_name: position
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity

  forward_velocity_controller:
    ros__parameters:
      joints:
        - rear_right_wheel_joint
        - rear_left_wheel_joint
        - front_right_wheel_joint
        - front_left_wheel_joint
      interface_name: velocity
      command_interfaces:
        - velocity
      state_interfaces:
        - position
        - velocity
        - effort