<?xml version="1.0"?>
<robot name="hunter_se_gazebo" xmlns:xacro="http://wiki.ros.org/xacro">
    <xacro:macro name="ackermann_control">
        <gazebo>
            <!-- <plugin name="gazebo_ros_ackermann_drive" filename="libgazebo_ros_ackermann_drive.so">
                <update_rate>100.0</update_rate>
                <ros>
                    <namespace>${robot_namespace}</namespace>
                    <remapping>odom:=wheel/odometry</remapping>
                    <remapping>distance:=wheel/distance</remapping>
                </ros>
                <initial_orientation_as_reference>true</initial_orientation_as_reference>


                <front_right_joint>front_right_wheel_joint</front_right_joint>
                <front_left_joint>front_left_wheel_joint</front_left_joint>
                <rear_right_joint>rear_right_wheel_joint</rear_right_joint>
                <rear_left_joint>rear_left_wheel_joint</rear_left_joint>

                <left_steering_joint>front_left_steer_joint</left_steering_joint>
                <right_steering_joint>front_right_steer_joint</right_steering_joint>

                <steering_wheel_joint>center_steer_joint</steering_wheel_joint>

                <wheel_base>${wheelbase}</wheel_base>
                <wheel_separation>${wheel_separation}</wheel_separation>
                <wheel_radius>${wheel_radius}</wheel_radius>
                <kingpin_width>${2* steering_axle_y_offset}</kingpin_width>

                <steering_limit>${max_steer}</steering_limit>
                <min_velocity>-5</min_velocity>
                <max_velocity>10</max_velocity>
                <min_aceleration>-2.5</min_aceleration>
                <max_acceleration>3.5</max_acceleration>
                <frameID>hunter_se/base_link</frameID>

                <publish_odom>true</publish_odom>
                <publish_odom_tf>true</publish_odom_tf>
                <publish_wheel_tf>true</publish_wheel_tf>
                <publish_distance>false</publish_distance>

                <odometry_frame>odom</odometry_frame>
                <robot_base_frame>base_link</robot_base_frame>
            </plugin> -->
            <!-- <plugin name="gazebo_ros_joint_state_publisher"
                filename="libgazebo_ros_joint_state_publisher.so">
                <ros>
                    <namespace>${robot_namespace}</namespace>
                </ros>

                <update_rate>20</update_rate>

                <joint_name>front_right_wheel_joint</joint_name>
                <joint_name>front_left_wheel_joint</joint_name>

            </plugin> -->
        </gazebo>
    </xacro:macro>
    <xacro:macro name="steering_control"
        params="
        name
        steer_limlow
        steer_limhigh">
        <joint name="${name}_steer_joint">
            <command_interface name="position">
                <param name="min">${steer_limlow}</param>
                <param name="max">${steer_limhigh}</param>
            </command_interface>
            <state_interface name="position" />
            <state_interface name="velocity" />
        </joint>
    </xacro:macro>
    <xacro:macro name="velocity_control"
        params="
        name
        velocity_limlow
        velocity_limhigh">
        <joint name="${name}_wheel_joint">
            <command_interface name="velocity">
                <param name="min">${velocity_limlow}</param>
                <param name="max">${velocity_limhigh}</param>
            </command_interface>
            <state_interface name="position" />
            <state_interface name="velocity" />
            <state_interface name="effort" />
        </joint>
    </xacro:macro>

</robot>